blueprint:
  name: HUE - Philips Friends of Hue Smart Switch (4 buttons)
  description: >
    Philips Friends of Hue Smart Switch (4 buttons)
  domain: automation
  source_url: https://github.com/briis/home-assistant-blueprints/blob/main/hue_foh_4_button_switch.yaml
  input:
    philipsfoh_sw:
      name: Friends of HUE Switch
      description: Philips Friends of Hue Smart Switch (4 buttons)
      selector:
        device:
          manufacturer: PhilipsFoH
          multiple: false
    button_UL_short_press:
      name: Upper Left  Button single press
      description: Action to run on button upper-left single press
      default: []
      selector:
        action: {}
    button_UR_short_press:
      name: Upper Right  Button single press
      description: Action to run on button upper-right single press
      default: []
      selector:
        action: {}
    button_LL_short_press:
      name: Lower Left  Button single press
      description: Action to run on button lower-left single press
      default: []
      selector:
        action: {}
    button_LR_short_press:
      name: Lower Right  Button single press
      description: Action to run on button lower-right single press
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: hue_event
    event_data:
      device_id: !input philipsfoh_sw
action:
  - variables:
      command: "{{ trigger.event.data.type }}"
      button_id: "{{ trigger.event.data.subtype }}"
      unique_id: "{{ trigger.event.data.unique_id }}"
  - choose:
      - conditions: "{{ command == 'short_release' and button_id == 1 }}"
        sequence: !input "button_UL_short_press"
      - conditions: "{{ command == 'short_release' and button_id == 2 }}"
        sequence: !input "button_LL_short_press"
      - conditions: "{{ command == 'short_release' and button_id == 3 }}"
        sequence: !input "button_UR_short_press"
      - conditions: "{{ command == 'short_release' and button_id == 4 }}"
        sequence: !input "button_LR_short_press"
