blueprint:
  name: ZHA Schneider Wiser Wireless Battery 4 button switch
  description: Automate Schneider Wiser Wireless Battery 4 button switch remote by ZHA events.
  domain: automation
  input:
    schneider_wiser_sw:
      name: Schneider Wiser Wireless Battery 4 button switch
      description: Wiser Wireless Battery 4 button switch 550D6001
      selector:
        device:
          integration: zha
          manufacturer: Schneider Electric
          model: FLS/AIRLINK/4
          multiple: false
    button_UL_short_press:
      name: Upper Left  Button single press
      description: Action to run on button upper-left single press
      default: []
      selector:
        action: {}
    button_UR_short_press:
      name: Upper Right Button single press
      description: Action to run on button upper-right single press
      default: []
      selector:
        action: {}
    button_LL_short_press:
      name: Lower left Button single press
      description: Action to run on button lower-left single press
      default: []
      selector:
        action: {}
    button_LR_short_press:
      name: Lower Right Button single press
      description: Action to run on button lower-right single press
      default: []
      selector:
        action: {}
source_url: https://github.com/briis/home-assistant-blueprints/blob/main/zha-wiser-wireless-battery-switch.yaml
mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input schneider_wiser_sw
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
  - choose:
      - conditions: "{{ command == 'on' and endpoint_id == 21 }}"
        sequence: !input button_UL_short_press
      - conditions: "{{ command == 'off' and endpoint_id == 21 }}"
        sequence: !input button_UR_short_press
      - conditions: "{{ command == 'on' and endpoint_id == 22 }}"
        sequence: !input button_LL_short_press
      - conditions: "{{ command == 'off' and endpoint_id == 22 }}"
        sequence: !input button_LR_short_press
