blueprint:
  name: Zigbee2Mqtt LK Fuga Wiser 4-Button Switch for Light and Dimming
  description:
    "#### Automate Schneider Wiser 4-Button Battery Switch by Zigbee2Mqtt
    events.\nThis Blueprint is specific for controlling Lights. It support 2 different
    light (or Light Groups). One for the Upper Bar and one for the Lower Bar. \nThe
    Buttons are paired as follows:\n* Upper Left button Short Press: Turn On Light
    1\n* Upper Right button Short Press: Turn of Light 1\n* Upper Left button Long
    Press: Dim the Light 1 Up\n* Upper Right button Long Press: Dim the Light 1 down\n*
    Lower Left button Short Press: Turn On Light 2\n* Lower Right button Short Press:
    Turn of Light 2\n* Lower Left button Long Press: Dim the Light 2 Up\n* Lower Right
    button Long Press: Dim the Light 2 down\n"
  domain: automation
  input:
    schneider_wiser_sw:
      name: LK Fuga Wiser Battery Operated 4-button Device
      description: MQTT Action topic to listen for (Ex. zigbee2mqtt/fuga_switch/action)
      selector:
        text: {}
    light_device_1:
      name: Light(s) for the Upper Bar
      description: Choose the Light entities to be controlled by the Upper Bar buttons
      selector:
        target:
          entity:
            - domain:
                - light
    color_light_1:
      name: Color Temperature for Light 1
      description: Color temperature in mireds.
      default: 350
      selector:
        color_temp:
          min_mireds: 160
          max_mireds: 500
    brightness_light_1:
      name: Brightness for Light 1
      description:
        Number indicating the percentage of full brightness, where 0 turns
        the light off, 1 is the minimum brightness, and 100 is the maximum brightness.
      default: 90
      selector:
        number:
          min: 0.0
          max: 100.0
          unit_of_measurement: "%"
          step: 5.0
          mode: slider
    light_device_2:
      name: Light(s) for the Lower Bar
      description: Choose the Light entities to be controlled by the Lower Bar buttons
      default: {}
      selector:
        target:
          entity:
            - domain:
                - light
    color_light_2:
      name: Color Temperature for Light 2
      description: Color temperature in mireds.
      default: 350
      selector:
        color_temp:
          min_mireds: 160
          max_mireds: 500
    brightness_light_2:
      name: Brightness for Light 2
      description:
        Number indicating the percentage of full brightness, where 0 turns
        the light off, 1 is the minimum brightness, and 100 is the maximum brightness.
      default: 90
      selector:
        number:
          min: 0.0
          max: 100.0
          unit_of_measurement: "%"
          step: 5.0
          mode: slider
    step_size:
      name: Brightness step value
      description: Change brightness by an amount.
      default: 25
      selector:
        number:
          min: 5.0
          max: 50.0
          step: 5.0
          mode: slider
  source_url: https://raw.githubusercontent.com/briis/home-assistant-blueprints/main/zigbee2mqtt/Z2M-Wiser-4-button-battery-light-control.yaml
mode: restart
max_exceeded: silent
trigger:
  - platform: mqtt
    topic: !input schneider_wiser_sw
    payload: on_top
    id: ul_short
  - platform: mqtt
    topic: !input schneider_wiser_sw
    payload: on_bottom
    id: ll_short
  - platform: mqtt
    topic: !input schneider_wiser_sw
    payload: off_top
    id: ur_short
  - platform: mqtt
    topic: !input schneider_wiser_sw
    payload: off_bottom
    id: lr_short
  - platform: mqtt
    topic: !input schneider_wiser_sw
    payload: brightness_move_up_top
    id: ul_long
  - platform: mqtt
    topic: !input schneider_wiser_sw
    payload: brightness_move_down_top
    id: ur_long
  - platform: mqtt
    topic: !input schneider_wiser_sw
    payload: brightness_move_up_bottom
    id: ll_long
  - platform: mqtt
    topic: !input schneider_wiser_sw
    payload: brightness_move_down_bottom
    id: lr_long
  - platform: mqtt
    topic: !input schneider_wiser_sw
    payload: brightness_stop_bottom
    id: l_stop
  - platform: mqtt
    topic: !input schneider_wiser_sw
    payload: brightness_stop_top
    id: u_stop
action:
  - variables:
      light_upper: !input light_device_1
      light_lower: !input light_device_2
      step_size: !input step_size
      step_up: "{{ step_size * 1 }}"
      step_down: "{{ step_size * -1 }}"
      dim_delay: 500
      brightness_val_1: !input brightness_light_1
      brightness_val_2: !input brightness_light_2
  - choose:
      - conditions:
          - condition: trigger
            id: ul_short
        sequence:
          - if:
              - condition: template
                value_template: "{{ brightness_val_1 == 0 }}"
            then:
              - service: light.turn_on
                data:
                  transition: 1
                  color_temp: !input color_light_1
                target: !input light_device_1
            else:
              - service: light.turn_on
                data:
                  transition: 1
                  color_temp: !input color_light_1
                  brightness_pct: !input brightness_light_1
                target: !input light_device_1
      - conditions:
          - condition: trigger
            id: ur_short
        sequence:
          - service: light.turn_off
            data: {}
            target: !input light_device_1
      - conditions:
          - condition: trigger
            id: ul_long
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: ul_long
              sequence:
                - service: light.turn_on
                  data:
                    transition: 1
                    brightness_step: "{{ step_up }}"
                  target: !input light_device_1
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: "{{ dim_delay | float }}"
      - conditions:
          - condition: trigger
            id: ur_long
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: ur_long
              sequence:
                - service: light.turn_on
                  data:
                    transition: 1
                    brightness_step: "{{ step_down }}"
                  target: !input light_device_1
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: "{{ dim_delay | float }}"
      - conditions:
          - condition: trigger
            id: ll_short
        sequence:
          - if:
              - condition: template
                value_template: "{{ brightness_val_2 == 0 }}"
            then:
              - service: light.turn_on
                data:
                  transition: 1
                  color_temp: !input color_light_2
                target: !input light_device_2
            else:
              - service: light.turn_on
                data:
                  transition: 1
                  color_temp: !input color_light_2
                  brightness_pct: !input brightness_light_2
                target: !input light_device_2
      - conditions:
          - condition: trigger
            id: lr_short
        sequence:
          - service: light.turn_off
            data: {}
            target: !input light_device_2
      - conditions:
          - condition: trigger
            id: ll_long
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: ll_long
              sequence:
                - service: light.turn_on
                  data:
                    transition: 1
                    brightness_step: "{{ step_up }}"
                  target: !input light_device_2
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: "{{ dim_delay | float }}"
      - conditions:
          - condition: trigger
            id: lr_long
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: lr_long
              sequence:
                - service: light.turn_on
                  data:
                    transition: 1
                    brightness_step: "{{ step_down }}"
                  target: !input light_device_2
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: "{{ dim_delay | float }}"
